/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <cstddef>
#include <android/log.h>
#include <string.h>
/* Header for class com_letv_jr_safesignaturelibrary_JrSignature */

#ifndef _Included_com_letv_jr_safesignaturelibrary_JrSignature
#define _Included_com_letv_jr_safesignaturelibrary_JrSignature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_letv_jr_safesignaturelibrary_JrSignature
 * Method:    getCLangString
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_letv_jr_safesignaturelibrary_JrSignature_getCompareInt(JNIEnv *, jclass , jobject);

#ifdef __cplusplus
}
#endif
#endif
